UKITH/Arabs-Startups

.gitignore

Setup folder structure

---

.gitignore
.travis.yml
package.json

Setup GitHub tools

---

package.json
tests/index.js

Setup testing

---

package.json
src/server.js
src/start_server.js

Setup express

---

database/db.js
database/db_build.js
database/schema.js
package.json

Setup database

---

.gitignore
.travis.yml
package.json

Fix Codecov

---

package.json
src/views/search_home.hbs

Home search View

---

README.md
src/start_server.js

Heroku setup

---

README.md

change the domain name on heroku

---

src/views/layouts/main.hbs
src/views/partials/navbar.hbs
src/views/search_results.hbs
src/views/startup_profile.hbs

Implement navbar

---

src/views/search_home.hbs

Submission form link

---

src/views/search_home.hbs

fix home search when searching by startup name

fix Home Search

---

src/routes/results.js

Bug any sector submission

---

src/views/search_results.hbs

Positioning of the startups in result page

---

src/views/All-news.hbs
src/views/all_news.hbs

All news View

---

src/views/news.hbs

VIew for news page

---

database/news_schema.js

News schema

---

src/views/not_found.hbs

Change the error page message

---

database/events_schema.js
public/style.css
src/server.js
src/views/all_events.hbs

Styling to All Events page 

---

src/views/all_news.hbs
tests/server/index.js

All News Page Styling

---

src/views/event.hbs
tests/server/index.js

related to #124 
Note: since the map PR is not merged yet i used a picture from the framework instead of the map for now.

Style single event page

---

src/helpers/date_to_string.js
src/server.js
src/views/news.hbs
tests/server/index.js

Single news page styling

---

src/views/partials/navbar.hbs
src/views/search_home.hbs
tests/server/index.js

Fix navbar functionality

---

src/views/search_home.hbs

rel #81 
@esraajb i wanted to ask if the links (for the popular searches ) should have a special functionality to render them or is it through the admin of the website ?

Search input Features

---

src/views/search_home.hbs
src/views/search_results.hbs

Hover Cursor

---

src/views/search_home.hbs

rel #141
it was all white before and blended in with the background

change color of the options in the dropdown menus in home

---

src/views/all_events.hbs

rel #152
@esraajb @Suuuuha Is this literally it (the change that needs to be done)?

All events page title

---

src/views/layouts/main.hbs
src/views/partials/navbar.hbs
src/views/search_results.hbs

Move search to nav-bar

---

public/sub_msg.js
src/routes/register_startup.js
src/views/submit_message.hbs

Fix link to the Submit Message page

---

src/views/search_home.hbs

fix typos 

---

src/views/all_events.hbs

Link to events

---

database/startup_schema.js
src/routes/register_startup.js
src/views/search_home.hbs
tests/server/index.js

Add 'sign up reason' section to the form

---

src/routes/register_startup.js
tests/server/index.js

Handle error if startup already exists

---

codecov.yml

Codecov.yml
